name: Kincher
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5765957
title: The Kinch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#535c6b'
    - '#73859b'
    - '#ffffff'
    - '#afbfe0'
  brandStrength: 0.8125
  lightness: 0.8808511
  saturation: 0.812766
  rhythmicContrast: 0.5553191
purpose: []
